### ISSUE TITLE
very wrong results

### ISSUE THREAD

**Issue by BK8000L** [Ne00n/yammdb#1]
195.242.218.1 is in UA, not PL
95.85.117.1 is in TM, not DE
95.85.120.6 is in TM, not AT
216.250.11.1 is in TM, not RU
194.180.174.1 is in MD, not AT

geolite2 and free ipinfo.io got them right

**Comment by Ne00n** [comment]
These results are expected, if you know what the project does and what it doesn't do.
Also, the project is discontinued.

**Comment by BK8000L** [comment]
please update your readme with "accuracy is very low, the project is discontinued"

**Comment by Ne00n** [comment]
I will update the readme for discontinued however, the readme also says this:
" Currently we have Servers in the following locations, we use to take measurements."

Again, you need to understand what the project does and what it doesn't do.

**Comment by BK8000L** [comment]
"Again, you need to understand what the project does and what it doesn't do."
so please update your readme with more clear information, i still don't get why accuracy isn't mentioned. amount or location of your servers doesn't say anything to me.
someone is just going to use it and break their application
